# Enable/Disable linters
linters:
  enable:
    - errcheck
    - gosimple
    - unused
    - govet
    - ineffassign
    - staticcheck
    - revive
  disable:
    - dupl
    - depguard
    - godot
    - tagalign
    - gofumpt
    - wrapcheck
    - exhaustruct
    - gochecknoglobals
    - err113
    - gci
    - recvcheck
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused

linters-settings:
  gci:
    skip-generated: true
  cyclop:
    max-complexity: 20
  errorlint:
    comparison: false
    asserts: false # to enable error checking using switch
  lll:
    line-length: 150
    tab-width: 1
  funlen:
    lines: 200
    statements: 50
    ignore-comments: true
  tagliatelle:
    case:
      rules:
        json: snake
  varnamelen:
    max-distance: 6
    min-name-length: 2
    check-receiver: false
    check-return: true
    check-type-param: true
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - c
      - e
      - s
      - i
      - j
      - f
      - y
      - err

issues:
  exclude-rules:
    - linters:
        - lll
      source: "^// @" # avoid lll from checking comment meant to be used for swaggo

# Timeout for linters to run
timeout: 5m
