---
services:
  atec_api:
    container_name: atec_api
    command: ["/bin/sh", "-c", "make watch"]
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - ./private.pem:/app/private.pem # mount the private key here
      - ./config.yaml:/app/config.yaml
      - ./.modd:/app/.modd
      - ./main.go:/app/main.go
      - ./db:/app/db
      - ./internal:/app/internal
      - ./assets:/app/assets
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      # these environments value will be read if running the app with flag init-admin-account set.
      # never use these values in production
      - INIT_ADMIN_EMAIL=admin@example.com
      - INIT_ADMIN_PASSWORD=secure_password
      - INIT_ADMIN_USERNAME=admin

  postgres:
    container_name: atec_api_postgres
    image: postgres:14
    volumes:
      -  atec_api_postgres:/var/lib/postgresql/data
    environment:
    # never use these values in production
      - POSTGRES_USER=atec_api
      - POSTGRES_PASSWORD=atec_api_password
      - POSTGRES_DB=atec_api
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atec_api"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  redis:
    container_name: atec_api_redis
    image: redis:7.4.2-alpine3.21
    restart: unless-stopped
    command: redis-server


volumes:
  atec_api_postgres:
