---
services:
  postgres:
    container_name: atec_api_postgres
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      -  atec_api_postgres:/var/lib/postgresql/data
    environment:
    # never use these values in production
      - POSTGRES_USER=atec_api
      - POSTGRES_PASSWORD=atec_api_password
      - POSTGRES_DB=atec_api
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atec_api"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  redis:
    container_name: atec_api_redis
    image: redis:7.4.2-alpine3.21
    restart: unless-stopped
    command: redis-server
    ports:
      - "6379:6379"


volumes:
  atec_api_postgres:
