FROM golang:1.23.6-alpine3.21

RUN apk add make

WORKDIR /app

RUN mkdir db
RUN mkdir internal

RUN go mod init github.com/luckyAkbar/atec

COPY go.sum go.mod .
RUN go mod download

COPY Makefile .

RUN make install-swag
RUN make install-modd
RUN make install-linter

# unknowingly i use mockery version that requires go v1.24. will pending to add this
# RUN make install-mockery