// Code generated by mockery v2.52.2. DO NOT EDIT.

package repository

import (
	context "context"

	model "github.com/luckyAkbar/atec/internal/model"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/luckyAkbar/atec/internal/repository"

	uuid "github.com/google/uuid"
)

// ChildRepositoryIface is an autogenerated mock type for the ChildRepositoryIface type
type ChildRepositoryIface struct {
	mock.Mock
}

type ChildRepositoryIface_Expecter struct {
	mock *mock.Mock
}

func (_m *ChildRepositoryIface) EXPECT() *ChildRepositoryIface_Expecter {
	return &ChildRepositoryIface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, input
func (_m *ChildRepositoryIface) Create(ctx context.Context, input repository.CreateChildInput) (*model.Child, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Child
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateChildInput) (*model.Child, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateChildInput) *model.Child); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Child)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateChildInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChildRepositoryIface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ChildRepositoryIface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input repository.CreateChildInput
func (_e *ChildRepositoryIface_Expecter) Create(ctx interface{}, input interface{}) *ChildRepositoryIface_Create_Call {
	return &ChildRepositoryIface_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *ChildRepositoryIface_Create_Call) Run(run func(ctx context.Context, input repository.CreateChildInput)) *ChildRepositoryIface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.CreateChildInput))
	})
	return _c
}

func (_c *ChildRepositoryIface_Create_Call) Return(_a0 *model.Child, _a1 error) *ChildRepositoryIface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChildRepositoryIface_Create_Call) RunAndReturn(run func(context.Context, repository.CreateChildInput) (*model.Child, error)) *ChildRepositoryIface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *ChildRepositoryIface) FindByID(ctx context.Context, id uuid.UUID) (*model.Child, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Child
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Child, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Child); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Child)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChildRepositoryIface_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type ChildRepositoryIface_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ChildRepositoryIface_Expecter) FindByID(ctx interface{}, id interface{}) *ChildRepositoryIface_FindByID_Call {
	return &ChildRepositoryIface_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *ChildRepositoryIface_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ChildRepositoryIface_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ChildRepositoryIface_FindByID_Call) Return(_a0 *model.Child, _a1 error) *ChildRepositoryIface_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChildRepositoryIface_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Child, error)) *ChildRepositoryIface_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, input
func (_m *ChildRepositoryIface) Search(ctx context.Context, input repository.SearchChildInput) ([]model.Child, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []model.Child
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.SearchChildInput) ([]model.Child, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.SearchChildInput) []model.Child); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Child)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.SearchChildInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChildRepositoryIface_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type ChildRepositoryIface_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - input repository.SearchChildInput
func (_e *ChildRepositoryIface_Expecter) Search(ctx interface{}, input interface{}) *ChildRepositoryIface_Search_Call {
	return &ChildRepositoryIface_Search_Call{Call: _e.mock.On("Search", ctx, input)}
}

func (_c *ChildRepositoryIface_Search_Call) Run(run func(ctx context.Context, input repository.SearchChildInput)) *ChildRepositoryIface_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.SearchChildInput))
	})
	return _c
}

func (_c *ChildRepositoryIface_Search_Call) Return(_a0 []model.Child, _a1 error) *ChildRepositoryIface_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChildRepositoryIface_Search_Call) RunAndReturn(run func(context.Context, repository.SearchChildInput) ([]model.Child, error)) *ChildRepositoryIface_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, input
func (_m *ChildRepositoryIface) Update(ctx context.Context, id uuid.UUID, input repository.UpdateChildInput) (*model.Child, error) {
	ret := _m.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Child
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, repository.UpdateChildInput) (*model.Child, error)); ok {
		return rf(ctx, id, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, repository.UpdateChildInput) *model.Child); ok {
		r0 = rf(ctx, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Child)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, repository.UpdateChildInput) error); ok {
		r1 = rf(ctx, id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChildRepositoryIface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ChildRepositoryIface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - input repository.UpdateChildInput
func (_e *ChildRepositoryIface_Expecter) Update(ctx interface{}, id interface{}, input interface{}) *ChildRepositoryIface_Update_Call {
	return &ChildRepositoryIface_Update_Call{Call: _e.mock.On("Update", ctx, id, input)}
}

func (_c *ChildRepositoryIface_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, input repository.UpdateChildInput)) *ChildRepositoryIface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(repository.UpdateChildInput))
	})
	return _c
}

func (_c *ChildRepositoryIface_Update_Call) Return(_a0 *model.Child, _a1 error) *ChildRepositoryIface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChildRepositoryIface_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, repository.UpdateChildInput) (*model.Child, error)) *ChildRepositoryIface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewChildRepositoryIface creates a new instance of ChildRepositoryIface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChildRepositoryIface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChildRepositoryIface {
	mock := &ChildRepositoryIface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
