// Code generated by mockery v2.52.2. DO NOT EDIT.

package repository

import mock "github.com/stretchr/testify/mock"

// ErrorUCAdapter is an autogenerated mock type for the ErrorUCAdapter type
type ErrorUCAdapter struct {
	mock.Mock
}

type ErrorUCAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *ErrorUCAdapter) EXPECT() *ErrorUCAdapter_Expecter {
	return &ErrorUCAdapter_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *ErrorUCAdapter) Execute(_a0 error) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(error) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ErrorUCAdapter_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ErrorUCAdapter_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 error
func (_e *ErrorUCAdapter_Expecter) Execute(_a0 interface{}) *ErrorUCAdapter_Execute_Call {
	return &ErrorUCAdapter_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *ErrorUCAdapter_Execute_Call) Run(run func(_a0 error)) *ErrorUCAdapter_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error))
	})
	return _c
}

func (_c *ErrorUCAdapter_Execute_Call) Return(_a0 error) *ErrorUCAdapter_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ErrorUCAdapter_Execute_Call) RunAndReturn(run func(error) error) *ErrorUCAdapter_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewErrorUCAdapter creates a new instance of ErrorUCAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewErrorUCAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ErrorUCAdapter {
	mock := &ErrorUCAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
