// Code generated by mockery v2.52.2. DO NOT EDIT.

package repository

import (
	context "context"

	model "github.com/luckyAkbar/atec/internal/model"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/luckyAkbar/atec/internal/repository"

	uuid "github.com/google/uuid"
)

// ResultRepositoryIface is an autogenerated mock type for the ResultRepositoryIface type
type ResultRepositoryIface struct {
	mock.Mock
}

type ResultRepositoryIface_Expecter struct {
	mock *mock.Mock
}

func (_m *ResultRepositoryIface) EXPECT() *ResultRepositoryIface_Expecter {
	return &ResultRepositoryIface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, input
func (_m *ResultRepositoryIface) Create(ctx context.Context, input repository.CreateResultInput) (*model.Result, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateResultInput) (*model.Result, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateResultInput) *model.Result); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateResultInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResultRepositoryIface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ResultRepositoryIface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input repository.CreateResultInput
func (_e *ResultRepositoryIface_Expecter) Create(ctx interface{}, input interface{}) *ResultRepositoryIface_Create_Call {
	return &ResultRepositoryIface_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *ResultRepositoryIface_Create_Call) Run(run func(ctx context.Context, input repository.CreateResultInput)) *ResultRepositoryIface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.CreateResultInput))
	})
	return _c
}

func (_c *ResultRepositoryIface_Create_Call) Return(_a0 *model.Result, _a1 error) *ResultRepositoryIface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ResultRepositoryIface_Create_Call) RunAndReturn(run func(context.Context, repository.CreateResultInput) (*model.Result, error)) *ResultRepositoryIface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllUserHistory provides a mock function with given fields: ctx, input
func (_m *ResultRepositoryIface) FindAllUserHistory(ctx context.Context, input repository.FindAllUserHistoryInput) ([]model.Result, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for FindAllUserHistory")
	}

	var r0 []model.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.FindAllUserHistoryInput) ([]model.Result, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.FindAllUserHistoryInput) []model.Result); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.FindAllUserHistoryInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResultRepositoryIface_FindAllUserHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllUserHistory'
type ResultRepositoryIface_FindAllUserHistory_Call struct {
	*mock.Call
}

// FindAllUserHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - input repository.FindAllUserHistoryInput
func (_e *ResultRepositoryIface_Expecter) FindAllUserHistory(ctx interface{}, input interface{}) *ResultRepositoryIface_FindAllUserHistory_Call {
	return &ResultRepositoryIface_FindAllUserHistory_Call{Call: _e.mock.On("FindAllUserHistory", ctx, input)}
}

func (_c *ResultRepositoryIface_FindAllUserHistory_Call) Run(run func(ctx context.Context, input repository.FindAllUserHistoryInput)) *ResultRepositoryIface_FindAllUserHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.FindAllUserHistoryInput))
	})
	return _c
}

func (_c *ResultRepositoryIface_FindAllUserHistory_Call) Return(_a0 []model.Result, _a1 error) *ResultRepositoryIface_FindAllUserHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ResultRepositoryIface_FindAllUserHistory_Call) RunAndReturn(run func(context.Context, repository.FindAllUserHistoryInput) ([]model.Result, error)) *ResultRepositoryIface_FindAllUserHistory_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *ResultRepositoryIface) FindByID(ctx context.Context, id uuid.UUID) (*model.Result, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Result, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Result); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResultRepositoryIface_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type ResultRepositoryIface_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ResultRepositoryIface_Expecter) FindByID(ctx interface{}, id interface{}) *ResultRepositoryIface_FindByID_Call {
	return &ResultRepositoryIface_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *ResultRepositoryIface_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ResultRepositoryIface_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ResultRepositoryIface_FindByID_Call) Return(_a0 *model.Result, _a1 error) *ResultRepositoryIface_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ResultRepositoryIface_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Result, error)) *ResultRepositoryIface_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, input
func (_m *ResultRepositoryIface) Search(ctx context.Context, input repository.SearchResultInput) ([]model.Result, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []model.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.SearchResultInput) ([]model.Result, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.SearchResultInput) []model.Result); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.SearchResultInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResultRepositoryIface_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type ResultRepositoryIface_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - input repository.SearchResultInput
func (_e *ResultRepositoryIface_Expecter) Search(ctx interface{}, input interface{}) *ResultRepositoryIface_Search_Call {
	return &ResultRepositoryIface_Search_Call{Call: _e.mock.On("Search", ctx, input)}
}

func (_c *ResultRepositoryIface_Search_Call) Run(run func(ctx context.Context, input repository.SearchResultInput)) *ResultRepositoryIface_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.SearchResultInput))
	})
	return _c
}

func (_c *ResultRepositoryIface_Search_Call) Return(_a0 []model.Result, _a1 error) *ResultRepositoryIface_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ResultRepositoryIface_Search_Call) RunAndReturn(run func(context.Context, repository.SearchResultInput) ([]model.Result, error)) *ResultRepositoryIface_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewResultRepositoryIface creates a new instance of ResultRepositoryIface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResultRepositoryIface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResultRepositoryIface {
	mock := &ResultRepositoryIface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
