// Code generated by mockery v2.52.2. DO NOT EDIT.

package usecase

import (
	context "context"

	model "github.com/luckyAkbar/atec/internal/model"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/luckyAkbar/atec/internal/usecase"

	uuid "github.com/google/uuid"
)

// ChildRepository is an autogenerated mock type for the ChildRepository type
type ChildRepository struct {
	mock.Mock
}

type ChildRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ChildRepository) EXPECT() *ChildRepository_Expecter {
	return &ChildRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, input
func (_m *ChildRepository) Create(ctx context.Context, input usecase.RepoCreateChildInput) (*model.Child, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Child
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.RepoCreateChildInput) (*model.Child, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.RepoCreateChildInput) *model.Child); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Child)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.RepoCreateChildInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChildRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ChildRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.RepoCreateChildInput
func (_e *ChildRepository_Expecter) Create(ctx interface{}, input interface{}) *ChildRepository_Create_Call {
	return &ChildRepository_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *ChildRepository_Create_Call) Run(run func(ctx context.Context, input usecase.RepoCreateChildInput)) *ChildRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.RepoCreateChildInput))
	})
	return _c
}

func (_c *ChildRepository_Create_Call) Return(_a0 *model.Child, _a1 error) *ChildRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChildRepository_Create_Call) RunAndReturn(run func(context.Context, usecase.RepoCreateChildInput) (*model.Child, error)) *ChildRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *ChildRepository) FindByID(ctx context.Context, id uuid.UUID) (*model.Child, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Child
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Child, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Child); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Child)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChildRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type ChildRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ChildRepository_Expecter) FindByID(ctx interface{}, id interface{}) *ChildRepository_FindByID_Call {
	return &ChildRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *ChildRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ChildRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ChildRepository_FindByID_Call) Return(_a0 *model.Child, _a1 error) *ChildRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChildRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Child, error)) *ChildRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, input
func (_m *ChildRepository) Search(ctx context.Context, input usecase.RepoSearchChildInput) ([]model.Child, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []model.Child
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.RepoSearchChildInput) ([]model.Child, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.RepoSearchChildInput) []model.Child); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Child)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.RepoSearchChildInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChildRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type ChildRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.RepoSearchChildInput
func (_e *ChildRepository_Expecter) Search(ctx interface{}, input interface{}) *ChildRepository_Search_Call {
	return &ChildRepository_Search_Call{Call: _e.mock.On("Search", ctx, input)}
}

func (_c *ChildRepository_Search_Call) Run(run func(ctx context.Context, input usecase.RepoSearchChildInput)) *ChildRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.RepoSearchChildInput))
	})
	return _c
}

func (_c *ChildRepository_Search_Call) Return(_a0 []model.Child, _a1 error) *ChildRepository_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChildRepository_Search_Call) RunAndReturn(run func(context.Context, usecase.RepoSearchChildInput) ([]model.Child, error)) *ChildRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, input
func (_m *ChildRepository) Update(ctx context.Context, id uuid.UUID, input usecase.RepoUpdateChildInput) (*model.Child, error) {
	ret := _m.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Child
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, usecase.RepoUpdateChildInput) (*model.Child, error)); ok {
		return rf(ctx, id, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, usecase.RepoUpdateChildInput) *model.Child); ok {
		r0 = rf(ctx, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Child)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, usecase.RepoUpdateChildInput) error); ok {
		r1 = rf(ctx, id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChildRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ChildRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - input usecase.RepoUpdateChildInput
func (_e *ChildRepository_Expecter) Update(ctx interface{}, id interface{}, input interface{}) *ChildRepository_Update_Call {
	return &ChildRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, input)}
}

func (_c *ChildRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, input usecase.RepoUpdateChildInput)) *ChildRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(usecase.RepoUpdateChildInput))
	})
	return _c
}

func (_c *ChildRepository_Update_Call) Return(_a0 *model.Child, _a1 error) *ChildRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChildRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, usecase.RepoUpdateChildInput) (*model.Child, error)) *ChildRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewChildRepository creates a new instance of ChildRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChildRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChildRepository {
	mock := &ChildRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
