// Code generated by mockery v2.52.2. DO NOT EDIT.

package usecase

import (
	context "context"

	model "github.com/luckyAkbar/atec/internal/model"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/luckyAkbar/atec/internal/usecase"

	uuid "github.com/google/uuid"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, input, txController
func (_m *UserRepository) Create(ctx context.Context, input usecase.RepoCreateUserInput, txController ...any) (*model.User, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, input)
	_ca = append(_ca, txController...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.RepoCreateUserInput, ...any) (*model.User, error)); ok {
		return rf(ctx, input, txController...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.RepoCreateUserInput, ...any) *model.User); ok {
		r0 = rf(ctx, input, txController...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.RepoCreateUserInput, ...any) error); ok {
		r1 = rf(ctx, input, txController...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.RepoCreateUserInput
//   - txController ...any
func (_e *UserRepository_Expecter) Create(ctx interface{}, input interface{}, txController ...interface{}) *UserRepository_Create_Call {
	return &UserRepository_Create_Call{Call: _e.mock.On("Create",
		append([]interface{}{ctx, input}, txController...)...)}
}

func (_c *UserRepository_Create_Call) Run(run func(ctx context.Context, input usecase.RepoCreateUserInput, txController ...any)) *UserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(usecase.RepoCreateUserInput), variadicArgs...)
	})
	return _c
}

func (_c *UserRepository_Create_Call) Return(_a0 *model.User, _a1 error) *UserRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_Create_Call) RunAndReturn(run func(context.Context, usecase.RepoCreateUserInput, ...any) (*model.User, error)) *UserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function with given fields: ctx, input, txController
func (_m *UserRepository) DeleteByID(ctx context.Context, input usecase.RepoDeleteUserByIDInput, txController ...any) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, input)
	_ca = append(_ca, txController...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.RepoDeleteUserByIDInput, ...any) error); ok {
		r0 = rf(ctx, input, txController...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type UserRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.RepoDeleteUserByIDInput
//   - txController ...any
func (_e *UserRepository_Expecter) DeleteByID(ctx interface{}, input interface{}, txController ...interface{}) *UserRepository_DeleteByID_Call {
	return &UserRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID",
		append([]interface{}{ctx, input}, txController...)...)}
}

func (_c *UserRepository_DeleteByID_Call) Run(run func(ctx context.Context, input usecase.RepoDeleteUserByIDInput, txController ...any)) *UserRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(usecase.RepoDeleteUserByIDInput), variadicArgs...)
	})
	return _c
}

func (_c *UserRepository_DeleteByID_Call) Return(_a0 error) *UserRepository_DeleteByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_DeleteByID_Call) RunAndReturn(run func(context.Context, usecase.RepoDeleteUserByIDInput, ...any) error) *UserRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function with given fields: ctx, email
func (_m *UserRepository) FindByEmail(ctx context.Context, email string) (*model.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type UserRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserRepository_Expecter) FindByEmail(ctx interface{}, email interface{}) *UserRepository_FindByEmail_Call {
	return &UserRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *UserRepository_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *UserRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepository_FindByEmail_Call) Return(_a0 *model.User, _a1 error) *UserRepository_FindByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_FindByEmail_Call) RunAndReturn(run func(context.Context, string) (*model.User, error)) *UserRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *UserRepository) FindByID(ctx context.Context, id uuid.UUID) (*model.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type UserRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *UserRepository_Expecter) FindByID(ctx interface{}, id interface{}) *UserRepository_FindByID_Call {
	return &UserRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *UserRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *UserRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserRepository_FindByID_Call) Return(_a0 *model.User, _a1 error) *UserRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.User, error)) *UserRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// IsAdminAccountExists provides a mock function with given fields: ctx
func (_m *UserRepository) IsAdminAccountExists(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsAdminAccountExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_IsAdminAccountExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAdminAccountExists'
type UserRepository_IsAdminAccountExists_Call struct {
	*mock.Call
}

// IsAdminAccountExists is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserRepository_Expecter) IsAdminAccountExists(ctx interface{}) *UserRepository_IsAdminAccountExists_Call {
	return &UserRepository_IsAdminAccountExists_Call{Call: _e.mock.On("IsAdminAccountExists", ctx)}
}

func (_c *UserRepository_IsAdminAccountExists_Call) Run(run func(ctx context.Context)) *UserRepository_IsAdminAccountExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UserRepository_IsAdminAccountExists_Call) Return(_a0 bool, _a1 error) *UserRepository_IsAdminAccountExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_IsAdminAccountExists_Call) RunAndReturn(run func(context.Context) (bool, error)) *UserRepository_IsAdminAccountExists_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, input
func (_m *UserRepository) Search(ctx context.Context, input usecase.RepoSearchUserInput) ([]model.User, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.RepoSearchUserInput) ([]model.User, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.RepoSearchUserInput) []model.User); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.RepoSearchUserInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type UserRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.RepoSearchUserInput
func (_e *UserRepository_Expecter) Search(ctx interface{}, input interface{}) *UserRepository_Search_Call {
	return &UserRepository_Search_Call{Call: _e.mock.On("Search", ctx, input)}
}

func (_c *UserRepository_Search_Call) Run(run func(ctx context.Context, input usecase.RepoSearchUserInput)) *UserRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.RepoSearchUserInput))
	})
	return _c
}

func (_c *UserRepository_Search_Call) Return(_a0 []model.User, _a1 error) *UserRepository_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_Search_Call) RunAndReturn(run func(context.Context, usecase.RepoSearchUserInput) ([]model.User, error)) *UserRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, input
func (_m *UserRepository) Update(ctx context.Context, userID uuid.UUID, input usecase.RepoUpdateUserInput) (*model.User, error) {
	ret := _m.Called(ctx, userID, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, usecase.RepoUpdateUserInput) (*model.User, error)); ok {
		return rf(ctx, userID, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, usecase.RepoUpdateUserInput) *model.User); ok {
		r0 = rf(ctx, userID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, usecase.RepoUpdateUserInput) error); ok {
		r1 = rf(ctx, userID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - input usecase.RepoUpdateUserInput
func (_e *UserRepository_Expecter) Update(ctx interface{}, userID interface{}, input interface{}) *UserRepository_Update_Call {
	return &UserRepository_Update_Call{Call: _e.mock.On("Update", ctx, userID, input)}
}

func (_c *UserRepository_Update_Call) Run(run func(ctx context.Context, userID uuid.UUID, input usecase.RepoUpdateUserInput)) *UserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(usecase.RepoUpdateUserInput))
	})
	return _c
}

func (_c *UserRepository_Update_Call) Return(_a0 *model.User, _a1 error) *UserRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_Update_Call) RunAndReturn(run func(context.Context, uuid.UUID, usecase.RepoUpdateUserInput) (*model.User, error)) *UserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
