name: GolangCI-Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.62.2