name: GolangCI-Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Download modules
        run: go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v1.60.3
          args: >-
            --print-issued-lines=false
            --exclude-use-default=false
            --enable=goimports
            --enable=unconvert
            --enable=unparam
            --concurrency=4
            --timeout=5m
            --modules-download-mode=mod