name: GolangCI-Lint

on:
  pull_request:
    branches:
      - 'master' # Trigger on pull requests to any branch
    workflow_call:
    
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.6' # Adjust the Go version to match your project

    - name: Install GolangCI-Lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.62.2

    - name: Run GolangCI-Lint
      run: |
        golangci-lint run --print-issued-lines=false --exclude-use-default=false --enable=goimports --enable=unconvert --enable=unparam --concurrency=4
