name: Mock Generation Check

on:
  workflow_call:

jobs:
  verify-mocks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install mockery
        run: make install-mockery

      - name: Generate mocks
        run: make mocks || exit 1

      - name: Check for uncommitted mock changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Error: There are uncommitted mock changes. Please run 'make mocks' locally and commit the changes."
            git status
            git diff
            exit 1
          fi