name: Mock Generation Check

on:
  workflow_call:
    inputs:
      pull_request_number:
        required: true
        type: number

jobs:
  verify-mocks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
<<<<<<< HEAD
          go-version: '1.23.6'
=======
          go-version: ${{ env.GO_VERSION }}
>>>>>>> 49b7634 (fix: sync and fix the pipeline order of execution)

      - name: Install mockery
        run: make install-mockery

      - name: Generate mocks
        run: make mocks || exit 1

      - name: Check for uncommitted mock changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Error: There are uncommitted mock changes. Please run 'make mocks' locally and commit the changes."
            git status
            git diff
            exit 1
          fi

      - name: Comment PR on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.payload.pull_request ? context.payload.pull_request.number : null;

            if (!issue_number) {
              console.log("No pull request number found. Skipping comment.");
              return;
            }

            github.rest.issues.createComment({
              issue_number: issue_number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: '❌ Mock files are out of date. Please run `mockery` locally and commit the changes.'
            })