# .github/workflows/mocks.yaml
name: Mock Generation Check

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  verify-mocks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.3'

      - name: Install mockery
        run: make install-mockery

      - name: Generate mocks
        run: make mocks

      - name: Check for uncommitted mock changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Error: There are uncommitted mock changes. Please run 'make mocks' locally and commit the changes."
            git status
            git diff
            exit 1
          fi

      - name: Comment PR on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: '❌ Mock files are out of date. Please run `mockery` locally and commit the changes.'
            })