name: PR Checks

env:
  GO_VERSION: '1.22.3'

on:
  pull_request:
    branches: [ master ]
  workflow_call:  # Allow this workflow to be called manually or by other workflows

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  mocks:
    needs: lint  # Ensure mocks runs only if lint succeeds
    uses: ./.github/workflows/mocks.yaml
  
  unit-test:
    needs: mocks  # Ensure unit-test runs only if mocks succeeds
    uses: ./.github/workflows/unit-test.yaml